// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle']
    copy: typeof import('./src/components/UserManagement copy.vue')['default']
    TTS: typeof import('./src/components/TTS.vue')['default']
    UserManagement: typeof import('./src/components/UserManagement.vue')['default']
    UserManagementAllInOne: typeof import('./src/components/UserManagement-All-In-One.vue')['default']
  }
}
